.SH "GENERAL USE"
Most users of will want to:
.LP
A) Run with --checkout to get a copy of the current configuration and
store it in a file.  The standard output can be redirected to a file
or a file can be specified with the --filename option.
.LP
B) Edit the configuration file with an editor.
.LP
C) Commit the configuration back using the --commit option and
specifying the configuration file with the --filename option.  The
configuration can be committed to multiple hosts in parallel via the
hostrange support.
.LP
Although not typically necessarily, some motherboards do not store
configuration values in non-volatile memory.  Therefore, after system
reboots, some configuration values may have changed.  The user may
wish to run configuration tools on each boot to ensure configuration
values remain.
