.SH "CONFIG OPTIONS"
The following options are used to read, write, and find differences
in configuration values.
.TP
\fB\-o\fR, \fB\-\-checkout\fR
Fetch configuration information.
.TP
\fB\-c\fR, \fB\-\-commit\fR
Update configuration information from a config file or key pairs.
.TP
\fB\-d\fR, \fB\-\-diff\fR
Show differences between stored information and a config file or key pairs.
.TP
\fB\-n\fR \fIFILENAME\fR, \fB\-\-filename\fR=\fIFILENAME\fR
Specify a config file for checkout/commit/diff.  If specified with checkout, cannot
use with multiple hosts or with \fB\-\-always\-prefix\fR.
.TP
\fB\-e\fR \fI"KEY=VALUE"\fR, \fB\-\-key\-pair\fR=\fI"KEY=VALUE"\fR
Specify KEY=VALUE pairs for checkout/commit/diff.  Specify KEY by
SectionName:FieldName.  This option can be used multiple times.  On
commit, any KEY=VALUE pairs will overwrite any pairs specified in a
file with \fB\-\-filename\fR.
.TP
\fB\-S\fR \fISECTION\fR, \fB\-\-section\fR=\fISECTION\fR
Specify a SECTION for checkout.  This option can be used multiple times.
.TP
\fB\-L\fR, \fB\-\-listsections\fR
List available sections for checkout.  Some sections in the list may
not be checked out by default and may require verbosity to be
increased.
