#ifndef _IPMI_PEF_KEYS_H
#define _IPMI_PEF_KEYS_H

#define COMMUNITY_STRING_KEY_STRING                            "Community_String"

#define LAD_ALERT_DESTINATION_SELECTOR_KEY_STRING              "Alert_Destination_Selector"
#define LAD_ALERT_DESTINATION_TYPE_KEY_STRING                  "Alert_Destination_Type"
#define LAD_ALERT_ACKNOWLEDGE_KEY_STRING                       "Alert_Acknowledge"
#define LAD_ALERT_ACKNOWLEDGE_TIMEOUT_KEY_STRING               "Alert_Acknowledge_Timeout"
#define LAD_ALERT_RETRIES_KEY_STRING                           "Alert_Retries"
#define LAD_ALERT_GATEWAY_KEY_STRING                           "Alert_Gateway"
#define LAD_ALERT_IP_ADDRESS_KEY_STRING                        "Alert_IP_Address"
#define LAD_ALERT_MAC_ADDRESS_KEY_STRING                       "Alert_MAC_Address"

#define APT_ALERT_POLICY_ENTRY_NUMBER_KEY_STRING               "Alert_Policy_Entry_Number"
#define APT_POLICY_TYPE_KEY_STRING                             "Policy_Type"
#define APT_POLICY_ENABLED_KEY_STRING                          "Policy_Enabled"
#define APT_POLICY_NUMBER_KEY_STRING                           "Policy_Number"
#define APT_DESTINATION_SELECTOR_KEY_STRING                    "Destination_Selector"
#define APT_CHANNEL_NUMBER_KEY_STRING                          "Channel_Number"
#define APT_ALERT_STRING_SET_SELECTOR_KEY_STRING               "Alert_String_Set_Selector"
#define APT_EVENT_SPECIFIC_ALERT_STRING_KEY_STRING             "Event_Specific_Alert_String"

#define FILTER_NUMBER_KEY_STRING                               "Filter_Number"
#define FILTER_TYPE_KEY_STRING                                 "Filter_Type"
#define ENABLE_FILTER_KEY_STRING                               "Enable_Filter"
#define EVENT_FILTER_ACTION_ALERT_KEY_STRING                   "Event_filter_Action_Alert"
#define EVENT_FILTER_ACTION_POWER_OFF_KEY_STRING               "Event_Filter_Action_Power_Off"
#define EVENT_FILTER_ACTION_RESET_KEY_STRING                   "Event_Filter_Action_Reset"
#define EVENT_FILTER_ACTION_POWER_CYCLE_KEY_STRING             "Event_Filter_Action_Power_Cycle"
#define EVENT_FILTER_ACTION_OEM_KEY_STRING                     "Event_Filter_Action_OEM"
#define EVENT_FILTER_ACTION_DIAGNOSTIC_INTERRUPT_KEY_STRING    "Event_Filter_Action_Diagnostic_Interrupt"
#define EVENT_FILTER_ACTION_GROUP_CONTROL_OPERATION_KEY_STRING "Event_Filter_Action_Group_Control_Operation"
#define ALERT_POLICY_NUMBER_KEY_STRING                         "Alert_Policy_Number"
#define GROUP_CONTROL_SELECTOR_KEY_STRING                      "Group_Control_Selector"
#define EVENT_SEVERITY_KEY_STRING                              "Event_Severity"
#define GENERATOR_ID_BYTE1_KEY_STRING                          "Generator_ID_Byte1"
#define GENERATOR_ID_BYTE2_KEY_STRING                          "Generator_ID_Byte2"
#define SENSOR_TYPE_KEY_STRING                                 "Sensor_Type"
#define SENSOR_NUMBER_KEY_STRING                               "Sensor_Number"
#define EVENT_TRIGGER_KEY_STRING                               "Event_Trigger"
#define EVENT_DATA1_OFFSET_MASK_KEY_STRING                     "Event_Data1_Offset_Mask"
#define EVENT_DATA1_AND_MASK_KEY_STRING                        "Event_Data1_AND_Mask"
#define EVENT_DATA1_COMPARE1_KEY_STRING                        "Event_Data1_Compare1"
#define EVENT_DATA1_COMPARE2_KEY_STRING                        "Event_Data1_Compare2"
#define EVENT_DATA2_AND_MASK_KEY_STRING                        "Event_Data2_AND_Mask"
#define EVENT_DATA2_COMPARE1_KEY_STRING                        "Event_Data2_Compare1"
#define EVENT_DATA2_COMPARE2_KEY_STRING                        "Event_Data2_Compare2"
#define EVENT_DATA3_AND_MASK_KEY_STRING                        "Event_Data3_AND_Mask"
#define EVENT_DATA3_COMPARE1_KEY_STRING                        "Event_Data3_Compare1"
#define EVENT_DATA3_COMPARE2_KEY_STRING                        "Event_Data3_Compare2"

#endif
