/*
 * Copyright (C) 2003-2015 FreeIPMI Core Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_COMMON_SPEC_H
#define IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_COMMON_SPEC_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Intel S5500WB/Penguin Computing Relion 700
 */
/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_PCIE_CORRECTABLE_SENSOR
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_RECEIVER_ERROR       0x00
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_BAD_DLLP             0x01
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_BAD_TLLP             0x02
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_REPLAY_NUM_ROLLOVER  0x03
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_REPLAY_TIMER_TIMEOUT 0x04
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_ADVISORY_NON_FATAL   0x05
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_SENSOR_LINK_BW_CHANGED      0x06

/*
 * String arrays for above
 */

extern const char * const ipmi_oem_intel_specific_pci_correctable_sensor[];
extern unsigned int ipmi_oem_intel_specific_pci_correctable_sensor_max_index;

/*
 * Intel S2600JF/Appro 512X
 * Intel S2600WP
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 * Intel S2600BPB
 */
/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_PCIE_FATAL_ERROR
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
/* achu: In earlier revisions for S2600JF & S2600WP, "_FROM_DOWNSTREAM" no included */
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_DATA_LINK_LAYER_PROTOCOL_ERROR         0x00
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_SURPRISE_LINK_DOWN_ERROR               0x01
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_COMPLETER_ABORT                        0x02
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_UNSUPPORTED_REQUEST                    0x03
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_POISONED_TLP                           0x04
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_FLOW_CONTROL_PROTOCOL                  0x05
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_COMPLETION_TIMEOUT                     0x06
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_RECEIVER_BUFFER_OVERFLOW               0x07
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_ACS_VIOLATION                          0x08
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_MALFORMED_TLP                          0x09
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_ECRC_ERROR                             0x0A
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_RECEIVED_FATAL_MESSAGE_FROM_DOWNSTREAM 0x0B
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_UNEXPECTED_COMPLETION                  0x0C
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_RECEIVED_NON_FATAL_MESSAGE             0x0D
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_UNCORRECTABLE_INTERNAL                 0x0E
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_MC_BLOCKED_TLP                         0x0F

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_PCIE_FATAL_ERROR_2
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
/* achu: not a typo, why a from from 0x01 to 0x0f? */
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_2_ATOMIC_EGRESS_BLOCKED           0x00
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_2_TLP_PREFIX_BLOCKED              0x01
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_FATAL_ERROR_2_UNSPECIFIED_NON_AER_FATAL_ERROR 0x0F

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_PCIE_CORRECTABLE_ERROR
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
/* achu: Similar to S5500WB, but some events text changed and new bitmasks, so new macros to differentiate */
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_RECEIVER_ERROR       0x00
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_BAD_DLLP             0x01
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_BAD_TLP              0x02
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_REPLAY_NUM_ROLLOVER  0x03
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_REPLAY_TIMER_TIMEOUT 0x04
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_ADVISORY_NON_FATAL   0x05
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_LINK_BW_CHANGED      0x06
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_CORRECTABLE_INTERNAL 0x07
#define IPMI_OEM_INTEL_SPECIFIC_PCIE_CORRECTABLE_ERROR_HEADER_LOG_OVERFLOW  0x08

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_QPI_FATAL_ERROR
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
/* achu: earlier code "OPI", assumed typo for "QPI" */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_LINK_LAYER_UNCORRECTABLE_ECC_ERROR             0x00
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_POISONED_PACKET_RECEPTION_ERROR 0x01
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_LINK_PHY_INIT_FAILURE                          0x02
/* achu: earlier S2600JF / S2600WP implementation prefixed next four with CSI */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PHY_LAYER_DETECTED_DRIFT_BUFFER_ALARM          0x03
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PHY_DETECTED_LATENCY_BUFFER_ROLLOVER           0x04
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PHY_INIT_FAILURE                               0x05
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_LINK_LAYER_GENERIC_CONTROL_ERROR               0x06
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PARITY_ERROR_IN_LINK_OR_PHY_LAYER              0x07
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_TIMEOUT_DETECTED                0x08
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_FAILED_RESPONSE                 0x09
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_ILLEGAL_PACKET_FIELD            0x0A
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_QUEUE_TABLE_OVERFLOW_UNDERFLOW  0x0B
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_VIRAL_ERROR                                    0x0C
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_PROTOCOL_LAYER_PARITY_ERROR                    0x0D
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_ROUTING_TABLE_ERROR                            0x0E

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_QPI_FATAL_ERROR_2
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_ILLEGAL_INBOUND_REQUEST                                      0x00
/* achu: earlier code used "OPI", assumed typo for "QPI" */
#if 0
/* achu: On S2600JF docs, Intel informed me there was an error in
 * their documentation and the following was not correct.  I'll leave
 * this here for legacy documentation
 */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_WRITE_CACHE_UNCORRECTABLE_DATA_ECC_ERROR                 0x01
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_WRITE_CACHE_UNCORRECTABLE_DATA_ECC_ERROR_2               0x02
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_WRITE_CACHE_UNCORRECTABLE_DATA_ECC_ERROR_3               0x03
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_RECEIVED_XPF_PHYSICAL_LOGICAL_REDIRECT_INTERRUPT_INBOUND 0x04
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_ILLEGAL_SAD_OR_ILLEGAL_OR_NON_EXISTENT_ADDRESS_OR_MEMORY 0x05
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_PCH_WRITE_CACHE_COHERENCY_VIOLATION                          0x06
#else  /* !0 */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_IIO_WRITE_CACHE_UNCORRECTABLE_DATA_ECC_ERROR                 0x01
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_IIO_CSR_CROSSING_32_BIT_BOUNDARY_ERROR                       0x02
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_IIO_RECEIVED_XPF_PHYSICAL_LOGICAL_REDIRECT_INTERRUPT_INBOUND 0x03
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_IIO_ILLEGAL_SAD_OR_ILLEGAL_OR_NON_EXISTENT_ADDRESS_OR_MEMORY 0x04
#define IPMI_OEM_INTEL_SPECIFIC_QPI_FATAL_ERROR_2_IIO_WRITE_CACHE_COHERENCY_VIOLATION                          0x05
#endif  /* !0 */

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_QPI_LINK_WIDTH_REDUCED
 * Sensor Type = IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT
 */
/* achu: not a typo, no 0x00 offset */
#define IPMI_OEM_INTEL_SPECIFIC_QPI_LINK_WIDTH_REDUCED_HALF_WIDTH    0x01
#define IPMI_OEM_INTEL_SPECIFIC_QPI_LINK_WIDTH_REDUCED_QUARTER_WIDTH 0x02

/*
 * String arrays for above
 */

/* achu: in earlier code S2600JF labeled "opi", assumed typo and is now "qpi" */
/* achu: in earlier code S2600JF labeled "pci", now is "pcie" */
extern const char * const ipmi_oem_intel_specific_pcie_fatal_error[];
extern unsigned int ipmi_oem_intel_specific_pcie_fatal_error_max_index;

extern const char * const ipmi_oem_intel_specific_pcie_fatal_error_2[];
extern unsigned int ipmi_oem_intel_specific_pcie_fatal_error_2_max_index;

extern const char * const ipmi_oem_intel_specific_pcie_correctable_error[];
extern unsigned int ipmi_oem_intel_specific_pcie_correctable_error_max_index;

extern const char * const ipmi_oem_intel_specific_qpi_fatal_error[];
extern unsigned int ipmi_oem_intel_specific_qpi_fatal_error_max_index;

extern const char * const ipmi_oem_intel_specific_qpi_fatal_error_2[];
extern unsigned int ipmi_oem_intel_specific_qpi_fatal_error_2_max_index;

extern const char * const ipmi_oem_intel_specific_qpi_link_width_reduced[];
extern unsigned int ipmi_oem_intel_specific_qpi_link_width_reduced_max_index;

/*
 * Intel S2600WP
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 * Intel S2600BPB
 */

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_FIRMWARE_UPDATE_STATUS_SENSOR
 * Sensor Type = IPMI_SENSOR_TYPE_VERSION_CHANGE
 */
/* achu: not a typo, no 0x00 offset */
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_UPDATE_STARTED                0x00
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_UPDATE_COMPLETED_SUCCESSFULLY 0x01
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_UPDATE_FAILURE                0x02

/*
 * String arrays for above
 */

extern const char * const ipmi_oem_intel_specific_firmware_update_status_sensor[];
extern unsigned int ipmi_oem_intel_specific_firmware_update_status_sensor_max_index;

/*
 * Intel S5500WB/Penguin Computing Relion 700
 * Quanta QSSC-S4R/Appro GB812X-CN
 * (Quanta motherboard contains Intel manufacturer ID)
 * Intel S2600JF/Appro 512X
 * Intel S2600WP
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 * Intel S2600BPB
 */

#define IPMI_OEM_INTEL_EVENT_DATA3_DEVICE_NUMBER_BITMASK   0xF8
#define IPMI_OEM_INTEL_EVENT_DATA3_DEVICE_NUMBER_SHIFT     3

#define IPMI_OEM_INTEL_EVENT_DATA3_FUNCTION_NUMBER_BITMASK 0x07
#define IPMI_OEM_INTEL_EVENT_DATA3_FUNCTION_NUMBER_SHIFT   0

/*
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 */

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_MIRRORING_DOMAIN_BITMASK 0xF0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_MIRRORING_DOMAIN_SHIFT   4

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_MIRRORING_DOMAIN_0 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_MIRRORING_DOMAIN_1 1

/*
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 * Intel S2600BPB
 */

#define IPMI_SENSOR_TYPE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED_EVENT_DATA2_OEM_INTEL_OUTPUT_VOLTAGE_FAULT      0x01
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED_EVENT_DATA2_OEM_INTEL_OUTPUT_POWER_FAULT        0x02
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED_EVENT_DATA2_OEM_INTEL_OUTPUT_OVER_CURRENT_FAULT 0x03
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED_EVENT_DATA2_OEM_INTEL_OVER_TEMPERATURE_FAULT    0x04
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED_EVENT_DATA2_OEM_INTEL_FAN_FAULT                 0x05

#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_OUTPUT_VOLTAGE_WARNING      0x01
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_OUTPUT_POWER_WARNING        0x02
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_OUTPUT_OVER_CURRENT_WARNING 0x03
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_OVER_TEMPERATURE_WARNING    0x04
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_FAN_WARNING                 0x05
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_INPUT_UNDER_VOLTAGE_WARNING 0x06
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_INPUT_OVER_CURRENT_WARNING  0x07
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_PREDICTIVE_FAILURE_EVENT_DATA2_OEM_INTEL_INPUT_OVER_POWER_WARNING    0x08

#define IPMI_SENSOR_TYPE_POWER_SUPPLY_CONFIGURATION_ERROR_EVENT_DATA2_OEM_INTEL_BMC_CANNOT_ACCESS_PMBUS      0x01
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_CONFIGURATION_ERROR_EVENT_DATA2_OEM_INTEL_PMBUS_REVISION_NOT_SUPPORTED 0x02
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_CONFIGURATION_ERROR_EVENT_DATA2_OEM_INTEL_PMBUS_REVISION_ERROR         0x03
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_CONFIGURATION_ERROR_EVENT_DATA2_OEM_INTEL_PSU_INCOMPATIBLE             0x04
#define IPMI_SENSOR_TYPE_POWER_SUPPLY_CONFIGURATION_ERROR_EVENT_DATA2_OEM_INTEL_PSU_FW_DEGRADED              0x05

#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_BITMASK 0x0F
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_SHIFT   0

#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_CPU1 0x01
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_CPU2 0x02
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_CPU3 0x04
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA2_OEM_INTEL_PROCESSOR_VRD_HOT_BITMAP_CPU4 0x08

#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU1_DIMM_CHANNEL_1_2 0x01
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU1_DIMM_CHANNEL_3_4 0x02
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU2_DIMM_CHANNEL_1_2 0x04
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU2_DIMM_CHANNEL_3_4 0x08
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU3_DIMM_CHANNEL_1_2 0x10
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU3_DIMM_CHANNEL_3_4 0x20
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU4_DIMM_CHANNEL_1_2 0x40
#define IPMI_SENSOR_TYPE_TEMPERATURE_EVENT_DATA3_OEM_INTEL_MEMORY_VRD_HOT_BITMAP_CPU4_DIMM_CHANNEL_3_4 0x80

#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_BITMASK 0xE0
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_SHIFT   5

#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_CHANNEL_BITMASK 0x18
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_CHANNEL_SHIFT   3

#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_DIMM_BITMASK 0x07
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_DIMM_SHIFT   0

#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_CPU1 0
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_CPU2 1
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_CPU3 2
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_SOCKET_ID_CPU4 3

#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_DIMM_1 0
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_DIMM_2 1
#define IPMI_SENSOR_TYPE_MEMORY_EVENT_DATA3_OEM_INTEL_DIMM_3 2

#define IPMI_SENSOR_TYPE_PROCESSOR_EVENT_DATA2_THERMAL_TRIP_OEM_INTEL_CPU_NON_RECOVERABLE_OVER_TEMP_CONDITION 0x00
#define IPMI_SENSOR_TYPE_PROCESSOR_EVENT_DATA2_THERMAL_TRIP_OEM_INTEL_CPU_BOOT_FIVR_FAULT                     0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_UNKNOWN        0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CATERR         0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CPU_CORE_ERROR 0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_MSID_MISMATCH  0x03

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA3_OEM_INTEL_CPU1 0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA3_OEM_INTEL_CPU2 0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA3_OEM_INTEL_CPU3 0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA3_OEM_INTEL_CPU4 0x08

#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_BITMASK 0x1F
#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_SHIFT   0

#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_UNCORE_MSR_REGISTER       0x01
#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_CORE_MSR_REGISTERS        0x02
#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_IIO_REGISTER              0x04
#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_PCI_CONFIG_SPACE          0x08
#define IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO_EVENT_DATA2_FAILED_REGISTER_TYPE_MCA_ERROR_SOURCE_REGISTER 0x10

#define IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT_EVENT_DATA2_OEM_INTEL_CPU_1 0
#define IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT_EVENT_DATA2_OEM_INTEL_CPU_2 1
#define IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT_EVENT_DATA2_OEM_INTEL_CPU_3 2
#define IPMI_SENSOR_TYPE_CRITICAL_INTERRUPT_EVENT_DATA2_OEM_INTEL_CPU_4 3

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_BITMASK 0x0F
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_SHIFT   0

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CPU1 0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CPU2 0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CPU3 0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_PROCESSOR_EVENT_DATA2_OEM_INTEL_CPU4 0x08

#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OEM_INTEL_CONFIG_ERROR_BITMASK 0x0F
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OEM_INTEL_CONFIG_ERROR_SHIFT   0

#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OEM_INTEL_CONFIG_ERROR_NONE                                    0
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OEM_INTEL_CONFIG_ERROR_INVALID_DIMM_CONFIGURATION_FOR_RAS_MODE 3

#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_BITMASK 0x0F
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_SHIFT   0

/* achu: Not a typo, lockstep = 2, rank sparing = 4, where is 3? */
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_NONE         0
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_MIRRORING    1
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_LOCKSTEP     2
#define IPMI_SENSOR_MEMORY_DEVICE_ENABLED_EVENT_DATA2_OR_EVENT_DATA3_OEM_INTEL_RAS_MODE_RANK_SPARING 4

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_RANK_ON_DIMM_BITMASK 0x03
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_RANK_ON_DIMM_SHIFT   0

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_BITMASK 0xF0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_SHIFT   4

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_A 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_B 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_C 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_SPARING_DOMAIN_D 3

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_BITMASK 0xE0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_SHIFT   5

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_BITMASK 0x18
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_SHIFT   3

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_DIMM_BITMASK 0x07
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_DIMM_SHIFT   0

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_CPU1 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_CPU2 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_CPU3 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_SOCKET_ID_CPU4 3

/* For CPU1 */
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_A 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_B 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_C 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_D 3

/* For CPU2 */
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_E 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_F 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_G 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_H 3

/* For CPU3 */
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_J 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_K 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_L 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_M 3

/* For CPU4 */
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_N 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_P 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_R 2
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_CHANNEL_T 3

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_DIMM_1 0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_DIMM_2 1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA3_DIMM_3 2

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_CHANNEL_INFORMATION_VALIDITY_CHECK_BITMASK 0x10
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_CHANNEL_INFORMATION_VALIDITY_CHECK_SHIFT   4

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_CHANNEL_INFORMATION_VALIDITY_CHECK_CHANNEL_NUMBER_VALID   1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_CHANNEL_INFORMATION_VALIDITY_CHECK_CHANNEL_NUMBER_INVALID 0

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_DIMM_INFORMATION_VALIDITY_CHECK_BITMASK 0x10
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_DIMM_INFORMATION_VALIDITY_CHECK_SHIFT   3

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_DIMM_INFORMATION_VALIDITY_CHECK_DIMM_SLOT_ID_VALID   1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_DIMM_INFORMATION_VALIDITY_CHECK_DIMM_SLOT_ID_INVALID 0

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_ERROR_TYPE_BITMASK 0x07
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_ERROR_TYPE_SHIFT   0

#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_ERROR_TYPE_PARITY_ERROR_TYPE_NOT_KNOWN      0x0
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_ERROR_TYPE_DATA_PARITY_ERROR                0x1
#define IPMI_SENSOR_TYPE_MEMORY_OEM_INTEL_EVENT_DATA2_ERROR_TYPE_COMMAND_AND_ADDRESS_PARITY_ERROR 0x3

#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_OF_UPDATE_BITMASK 0xF0
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_OF_UPDATE_SHIFT   4

#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_OF_UPDATE_BMC  0x0
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_OF_UPDATE_BIOS 0x1
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_OF_UPDATE_ME   0x2

#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_INSTANCE_BITMASK 0x0C
#define IPMI_OEM_INTEL_SPECIFIC_FIRMWARE_UPDATE_STATUS_SENSOR_EVENT_DATA2_TARGET_INSTANCE_SHIFT   2

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_BITMASK 0x07
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_SHIFT   0

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_CFG_SYNTAX_ERROR          0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_CHASSIS_AUTO_DETECT_ERROR 0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_SDR_CFG_FILE_MISMATCH     0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_SDR_OR_CFG_FILE_CORRUPTED 0x03
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED_MANAGEMENT_HEALTH_AUTO_CONFIG_ERROR_EVENT_DATA3_OEM_INTEL_SDR_SYNTAX_ERROR          0x04

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_BIOS_RECOVERY_START
 * Sensor Type = IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS
 */
/* achu: not a typo, no 0x00 offset */
#define IPMI_OEM_INTEL_SPECIFIC_BIOS_RECOVERY_START 0x01

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_BIOS_RECOVERY_COMPLETE
 * Sensor Type = IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS
 */
/* achu: not a typo, no 0x00 offset */
/* In S2600KP, S2600WT2, S2600WTT, S2600GZ timeframe, was "FINISH" instead of "COMPLETE" */
#define IPMI_OEM_INTEL_SPECIFIC_BIOS_RECOVERY_COMPLETE 0x01

/*
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO
 * Sensor Type = IPMI_SENSOR_TYPE_OEM_INTEL_IERR_RECOVERY_DUMP_INFO
 */
#define IPMI_OEM_INTEL_SPECIFIC_IERR_RECOVERY_DUMP_INFO_DUMP_FAILED 0x01

/*
 * String arrays for above
 */

extern const char * const ipmi_oem_intel_specific_bios_recovery_start[];
extern unsigned int ipmi_oem_intel_specific_bios_recovery_start_max_index;

extern const char * const ipmi_oem_intel_specific_bios_recovery_complete[];
extern unsigned int ipmi_oem_intel_specific_bios_recovery_complete_max_index;

extern const char * const ipmi_oem_intel_specific_ierr_recovery_dump_info[];
extern unsigned int ipmi_oem_intel_specific_ierr_recovery_dump_info_max_index;

/*
 * Intel S2600KP
 * Intel S2600WT2
 * Intel S2600WTT
 * Intel S2600GZ
 */

/* achu: labeling this BROADWELL, but may extend beyond this generation */

#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_SYSTEM_RTC_DATE_TIME_NOT_SET                                                       0x0012
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PASSWORD_CHECK_FAILED                                                              0x0048
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_COMPONENT_ENCOUNTERED_A_PERR_ERROR                                             0x0140
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_RESOURCE_CONFLICT                                                              0x0141
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_OUT_OF_RESOURCES_ERROR                                                         0x0146
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_CORE_THREAD_COUNT_MISMATCH_DETECTED                                      0x0191
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_CACHE_SIZE_MISMATCH_DETECTED                                             0x0192
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_FAMILY_MISMATCH_DETECTED                                                 0x0194
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_INTEL_QPI_LINK_FREQUENCIES_UNABLE_TO_SYNCHRONIZE                         0x0195
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_MODEL_MISMATCH_DETECTED                                                  0x0196
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_FREQUENCIES_UNABLE_TO_SYNCHRONIZE                                        0x0197
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BIOS_SETTINGS_RESET_TO_DEFAULT_SETTINGS                                            0x5220
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PASSWORDS_CLEARED_BY_JUMPER                                                        0x5221
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PASSWORD_CLEAR_JUMPER_IS_SET                                                       0x5224
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_01_DISABLED                                                              0x8130
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_02_DISABLED                                                              0x8131
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_03_DISABLED                                                              0x8132
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_04_DISABLED                                                              0x8133
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_01_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8160
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_02_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8161
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_03_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8162
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_04_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8163
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_01_FAILED_SELF_TEST_BIST                                                 0x8170
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_02_FAILED_SELF_TEST_BIST                                                 0x8171
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_03_FAILED_SELF_TEST_BIST                                                 0x8172
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_04_FAILED_SELF_TEST_BIST                                                 0x8173
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_01_MICROCODE_UPDATE_NOT_FOUND                                            0x8180
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_02_MICROCODE_UPDATE_NOT_FOUND                                            0x8181
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_03_MICROCODE_UPDATE_NOT_FOUND                                            0x8182
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PROCESSOR_04_MICROCODE_UPDATE_NOT_FOUND                                            0x8183
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_WATCHDOG_TIMER_FAILED_ON_LAST_BOOT                                                 0x8190
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_OS_BOOT_WATCHDOG_TIMER_FAILURE                                                     0x8198
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_FAILED_SELF_TEST                                   0x8300
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_HOT_SWAP_CONTROLLER_FAILURE                                                        0x8305
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_MANAGEMENT_ENGINE_ME_FAILED_SELF_TEST                                              0x83A0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_MANAGEMENT_ME_FAILED_TO_RESPOND                                                    0x83A1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_FAILED_TO_RESPOND                                  0x84F2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_IN_UPDATE_MODE                                     0x84F3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_SENSOR_DATA_RECORD_EMPTY                                                           0x84F4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_SYSTEM_EVENT_LOG_FULL                                                              0x84FF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_MEMORY_COMPONENT_COULD_NOT_BE_CONFIGURED_IN_THE_SELECTED_RAS_MODE                  0x8500
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_POPULATION_ERROR                                                              0x8501
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A1_FAILED_SELF_TEST_INITIALIZATION                                            0x8520
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A2_FAILED_SELF_TEST_INITIALIZATION                                            0x8521
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A3_FAILED_SELF_TEST_INITIALIZATION                                            0x8522
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B1_FAILED_SELF_TEST_INITIALIZATION                                            0x8523
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B2_FAILED_SELF_TEST_INITIALIZATION                                            0x8524
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B3_FAILED_SELF_TEST_INITIALIZATION                                            0x8525
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C1_FAILED_SELF_TEST_INITIALIZATION                                            0x8526
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C2_FAILED_SELF_TEST_INITIALIZATION                                            0x8527
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C3_FAILED_SELF_TEST_INITIALIZATION                                            0x8528
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D1_FAILED_SELF_TEST_INITIALIZATION                                            0x8529
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D2_FAILED_SELF_TEST_INITIALIZATION                                            0x852A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D3_FAILED_SELF_TEST_INITIALIZATION                                            0x852B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E1_FAILED_SELF_TEST_INITIALIZATION                                            0x852C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E2_FAILED_SELF_TEST_INITIALIZATION                                            0x852D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E3_FAILED_SELF_TEST_INITIALIZATION                                            0x852E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F1_FAILED_SELF_TEST_INITIALIZATION                                            0x852F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F2_FAILED_SELF_TEST_INITIALIZATION                                            0x8530
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F3_FAILED_SELF_TEST_INITIALIZATION                                            0x8531
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G1_FAILED_SELF_TEST_INITIALIZATION                                            0x8532
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G2_FAILED_SELF_TEST_INITIALIZATION                                            0x8533
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G3_FAILED_SELF_TEST_INITIALIZATION                                            0x8534
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H1_FAILED_SELF_TEST_INITIALIZATION                                            0x8535
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H2_FAILED_SELF_TEST_INITIALIZATION                                            0x8536
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H3_FAILED_SELF_TEST_INITIALIZATION                                            0x8537
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J1_FAILED_SELF_TEST_INITIALIZATION                                            0x8538
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J2_FAILED_SELF_TEST_INITIALIZATION                                            0x8539
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J3_FAILED_SELF_TEST_INITIALIZATION                                            0x853A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K1_FAILED_SELF_TEST_INITIALIZATION                                            0x853B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K2_FAILED_SELF_TEST_INITIALIZATION                                            0x853C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K3_FAILED_SELF_TEST_INITIALIZATION                                            0x853D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L1_FAILED_SELF_TEST_INITIALIZATION                                            0x853E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L2_FAILED_SELF_TEST_INITIALIZATION                                            0x853F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L3_FAILED_SELF_TEST_INITIALIZATION                                            0x85C0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M1_FAILED_SELF_TEST_INITIALIZATION                                            0x85C1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M2_FAILED_SELF_TEST_INITIALIZATION                                            0x85C2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M3_FAILED_SELF_TEST_INITIALIZATION                                            0x85C3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N1_FAILED_SELF_TEST_INITIALIZATION                                            0x85C4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N2_FAILED_SELF_TEST_INITIALIZATION                                            0x85C5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N3_FAILED_SELF_TEST_INITIALIZATION                                            0x85C6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P1_FAILED_SELF_TEST_INITIALIZATION                                            0x85C7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P2_FAILED_SELF_TEST_INITIALIZATION                                            0x85C8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P3_FAILED_SELF_TEST_INITIALIZATION                                            0x85C9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R1_FAILED_SELF_TEST_INITIALIZATION                                            0x85CA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R2_FAILED_SELF_TEST_INITIALIZATION                                            0x85CB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R3_FAILED_SELF_TEST_INITIALIZATION                                            0x85CC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T1_FAILED_SELF_TEST_INITIALIZATION                                            0x85CD
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T2_FAILED_SELF_TEST_INITIALIZATION                                            0x85CE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T3_FAILED_SELF_TEST_INITIALIZATION                                            0x85CF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A1_DISABLED                                                                   0x8540
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A2_DISABLED                                                                   0x8541
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A3_DISABLED                                                                   0x8542
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B1_DISABLED                                                                   0x8543
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B2_DISABLED                                                                   0x8544
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B3_DISABLED                                                                   0x8545
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C1_DISABLED                                                                   0x8546
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C2_DISABLED                                                                   0x8547
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C3_DISABLED                                                                   0x8548
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D1_DISABLED                                                                   0x8549
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D2_DISABLED                                                                   0x854A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D3_DISABLED                                                                   0x854B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E1_DISABLED                                                                   0x854C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E2_DISABLED                                                                   0x854D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E3_DISABLED                                                                   0x854E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F1_DISABLED                                                                   0x854F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F2_DISABLED                                                                   0x8550
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F3_DISABLED                                                                   0x8551
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G1_DISABLED                                                                   0x8552
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G2_DISABLED                                                                   0x8553
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G3_DISABLED                                                                   0x8554
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H1_DISABLED                                                                   0x8555
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H2_DISABLED                                                                   0x8556
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H3_DISABLED                                                                   0x8557
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J1_DISABLED                                                                   0x8558
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J2_DISABLED                                                                   0x8559
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J3_DISABLED                                                                   0x855A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K1_DISABLED                                                                   0x855B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K2_DISABLED                                                                   0x855C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K3_DISABLED                                                                   0x855D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L1_DISABLED                                                                   0x855E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L2_DISABLED                                                                   0x855F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L3_DISABLED                                                                   0x85D0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M1_DISABLED                                                                   0x85D1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M2_DISABLED                                                                   0x85D2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M3_DISABLED                                                                   0x85D3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N1_DISABLED                                                                   0x85D4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N2_DISABLED                                                                   0x85D5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N3_DISABLED                                                                   0x85D6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P1_DISABLED                                                                   0x85D7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P2_DISABLED                                                                   0x85D8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P3_DISABLED                                                                   0x85D9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R1_DISABLED                                                                   0x85DA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R2_DISABLED                                                                   0x85DB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R3_DISABLED                                                                   0x85DC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T1_DISABLED                                                                   0x85DD
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T2_DISABLED                                                                   0x85DE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T3_DISABLED                                                                   0x85DF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8560
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8561
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_A3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8562
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8563
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8564
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_B3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8565
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8566
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8567
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_C3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8568
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8569
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_D3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_E3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x856F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8570
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_F3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8571
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8572
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8573
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_G3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8574
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8575
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8576
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_H3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8577
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8578
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x8579
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_J3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_K3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x857F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_L3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_M3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_N3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_P3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85E9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85EA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85EB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_R3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85EC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T1_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85ED
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T2_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85EE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DIMM_T3_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE                            0x85EF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_POST_RECLAIM_OF_NON_CRITICAL_VARIABLES                                             0x8604
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BIOS_SETTINGS_ARE_CORRUPTED                                                        0x8605
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_NVRAM_VARIABLE_SPACE_WAS_CORRUPTED_AND_HAS_BEEN_REINITIALIZED                      0x8606
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_SERIAL_PORT_COMPONENT_WAS_NOT_DETECTED                                             0x92A3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_SERIAL_PORT_COMPONENT_ENCOUNTERED_A_RESOURCE_CONFLICT_ERROR                        0x92A9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_TPM_DEVICE_NOT_DETECTED                                                            0xA000
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_TPM_DEVICE_MISSING_OR_NOT_RESPONDING                                               0xA001
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_TPM_DEVICE_FAILURE                                                                 0xA002
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_TPM_DEVICE_FAILED_SELF_TEST                                                        0xA003
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_BIOS_ACM_ERROR                                                                     0xA100
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_COMPONENT_ENCOUNTERED_A_SERR_ERROR                                             0xA421
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_EXPRESS_COMPONENT_ENCOUNTERED_A_PERR_ERROR                                     0xA5A0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_PCI_EXPRESS_COMPONENT_ENCOUNTERED_A_SERR_ERROR                                     0xA5A1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_BROADWELL_POST_ERROR_CODE_DXE_BOOT_SERVICES_DRIVER_NOT_ENOUGH_MEMORY_AVAILABLE_TO_SHADOW_A_LEGACY_OPTION_ROM 0xA6A0

#ifdef __cplusplus
}
#endif

#endif /* IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_COMMON_SPEC_H */
