/*
 * Copyright (C) 2003-2015 FreeIPMI Core Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_S2600BPB_SPEC_H
#define IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_S2600BPB_SPEC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <freeipmi/spec/oem/intel/ipmi-sensor-and-event-code-tables-oem-intel-common-spec.h>

/*
 * S2600BPB
 */

/* Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_REDUNDANCY
 * or
 * Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_SENSOR_SPECIFIC
 * Sensor Type = IPMI_SENSOR_TYPE_MEMORY
 */
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA2_DIMM_INDEX_BITMASK 0xF0
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA2_DIMM_INDEX_SHIFT   4

#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA2_RANK_INDEX_BITMASK 0x0F
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA2_RANK_INDEX_SHIFT   0

#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_BITMASK 0xF0
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_SHIFT   4

#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_CPU1 0x0
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_CPU2 0x1
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_CPU3 0x2
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_SOCKET_INDEX_CPU4 0x3

#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_CHANNEL_INDEX_BITMASK 0x0F
#define IPMI_OEM_INTEL_S2600BPB_EVENT_DATA3_CHANNEL_INDEX_SHIFT   0

/* Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_NVME_CRITICAL_WARNING_SENSOR
 * Sensor Type = IPMI_SENSOR_TYPE_DISK_DRIVE
 */
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA1_DISK_DRIVE_BITMASK 0x04
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA1_DISK_DRIVE_SHIFT   0

#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA2_DISK_DRIVE_SPARE_SPACE_BELOW_THRESHOLD          0x01
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA2_DISK_DRIVE_TEMPERATURE_ABOVE_OR_BELOW_THRESHOLD 0x02
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA2_DISK_DRIVE_NVM_RELIABILITY_DEGRADED             0x04
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA2_DISK_DRIVE_IN_READ_ONLY_MODE                    0x08
#define IPMI_OEM_INTEL_S2600BPB_NVME_CRITICAL_WARNING_EVENT_DATA2_DISK_DRIVE_VOLATILE_BACKUP_SERVICE_FAILED       0x10

/* Sensor Type = IPMI_SENSOR_TYPE_SYSTEM_EVENT */
/* achu: this is not documented in IPMI spec, so assuming Intel OEM
 * extension?  Or possibly extension not yet released by Intel? */
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_IMAGE_IS_UPLOADED 0x07
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_IMAGE_IS_LOST     0x08

#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA2_BIOS_CONFIGURATION_TABLE  0x00
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA2_BIOS_CONFIGURATION_CHANGE 0x01
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA2_BIOS_IMAGE                0x02
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA2_ME_IMAGE                  0x03
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA2_FD_IMAGE                  0x04

#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA3_FIRMWARE_UPDATE           0x00
#define IPMI_SENSOR_TYPE_SYSTEM_EVENT_OEM_INTEL_S2600BPB_EVENT_DATA3_BIOS_CONFIGURATION        0x01

/* Sensor Type = IPMI_SENSOR_TYPE_SESSION_AUDIT
 * Offset = IPMI_SENSOR_TYPE_SESSION_AUDIT_INVALID_USERNAME_OR_PASSWORD
 *          IPMI_SENSOR_TYPE_SESSION_AUDIT_INVALID_PASSWORD_DISABLE
 */
#define IPMI_SENSOR_TYPE_SESSION_AUDIT_EVENT_DATA2_OEM_INTEL_S2600BPB_USERID_BITMASK 0x3F
#define IPMI_SENSOR_TYPE_SESSION_AUDIT_EVENT_DATA2_OEM_INTEL_S2600BPB_USERID_SHIFT   0

/* achu: Note this is different compared to other INTEL CHANNEL bitmasks */
#define IPMI_SENSOR_TYPE_SESSION_AUDIT_EVENT_DATA3_OEM_INTEL_S2600BPB_CHANNEL_BITMASK 0x0F
#define IPMI_SENSOR_TYPE_SESSION_AUDIT_EVENT_DATA3_OEM_INTEL_S2600BPB_CHANNEL_SHIFT   0

/* achu: labeling this SKYLAKE, but may extend beyond this generation */

#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_SYSTEM_RTC_DATE_TIME_NOT_SET                                                       0x0012
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PASSWORD_CHECK_FAILED                                                              0x0048
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_COMPONENT_ENCOUNTERED_A_PERR_ERROR                                             0x0140
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_RESOURCE_CONFLICT                                                              0x0141
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_OUT_OF_RESOURCES_ERROR                                                         0x0146
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_CORE_THREAD_COUNT_MISMATCH_DETECTED                                      0x0191
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_CACHE_SIZE_MISMATCH_DETECTED                                             0x0192
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_FAMILY_MISMATCH_DETECTED                                                 0x0194
/* UPI in doc, assuming typo and should be QPI */
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_INTEL_QPI_LINK_FREQUENCIES_UNABLE_TO_SYNCHRONIZE                         0x0195
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_MODEL_MISMATCH_DETECTED                                                  0x0196
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_FREQUENCIES_UNABLE_TO_SYNCHRONIZE                                        0x0197
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BIOS_SETTINGS_RESET_TO_DEFAULT_SETTINGS                                            0x5220
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PASSWORDS_CLEARED_BY_JUMPER                                                        0x5221
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PASSWORD_CLEAR_JUMPER_IS_SET                                                       0x5224
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_01_DISABLED                                                              0x8130
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_02_DISABLED                                                              0x8131
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_01_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8160
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_02_UNABLE_TO_APPLY_MICROCODE_UPDATE                                      0x8161
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_01_FAILED_SELF_TEST_BIST                                                 0x8170
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_02_FAILED_SELF_TEST_BIST                                                 0x8171
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_01_MICROCODE_UPDATE_NOT_FOUND                                            0x8180
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PROCESSOR_02_MICROCODE_UPDATE_NOT_FOUND                                            0x8181
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_WATCHDOG_TIMER_FAILED_ON_LAST_BOOT                                                 0x8190
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_OS_BOOT_WATCHDOG_TIMER_FAILURE                                                     0x8198
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_FAILED_SELF_TEST                                   0x8300
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_HOT_SWAP_CONTROLLER_FAILURE                                                        0x8305
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MANAGEMENT_ENGINE_ME_FAILED_SELF_TEST                                              0x83A0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MANAGEMENT_ME_FAILED_TO_RESPOND                                                    0x83A1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_FAILED_TO_RESPOND                                  0x84F2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_IN_UPDATE_MODE                                     0x84F3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BASEBOARD_MANAGEMENT_CONTROLLER_SENSOR_DATA_RECORD_EMPTY                           0x84F4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_SYSTEM_EVENT_LOG_FULL                                                              0x84FF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_COMPONENT_COULD_NOT_BE_CONFIGURED_IN_THE_SELECTED_RAS_MODE                  0x85FC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_POPULATION_ERROR                                                            0x8501
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_A1                                     0x8520
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_A2                                     0x8521
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_A3                                     0x8522
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_B1                                     0x8523
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_B2                                     0x8524
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_B3                                     0x8525
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_C1                                     0x8526
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_C2                                     0x8527
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_C3                                     0x8528
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_D1                                     0x8529
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_D2                                     0x852A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_D3                                     0x852B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_E1                                     0x852C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_E2                                     0x852D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_E3                                     0x852E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_F1                                     0x852F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_F2                                     0x8530
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_F3                                     0x8531
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_G1                                     0x8532
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_G2                                     0x8533
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_G3                                     0x8534
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_H1                                     0x8535
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_H2                                     0x8536
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU1_DIMM_H3                                     0x8537

#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_A1                                     0x8538
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_A2                                     0x8539
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_A3                                     0x853A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_B1                                     0x853B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_B2                                     0x853C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_B3                                     0x853D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_C1                                     0x853E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_C2                                     0x853F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_C3                                     0x85C0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_D1                                     0x85C1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_D2                                     0x85C2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_D3                                     0x85C3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_E1                                     0x85C4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_E2                                     0x85C5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_E3                                     0x85C6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_F1                                     0x85C7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_F2                                     0x85C8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_F3                                     0x85C9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_G1                                     0x85CA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_G2                                     0x85CB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_G3                                     0x85CC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_H1                                     0x85CD
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_H2                                     0x85CE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_FAILED_TEST_INITIALIZATION_CPU2_DIMM_H3                                     0x85CF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_A1                                                       0x8540
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_A2                                                       0x8541
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_A3                                                       0x8542
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_B1                                                       0x8543
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_B2                                                       0x8544
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_B3                                                       0x8545
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_C1                                                       0x8546
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_C2                                                       0x8547
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_C3                                                       0x8548
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_D1                                                       0x8549
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_D2                                                       0x854A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_D3                                                       0x854B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_E1                                                       0x854C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_E2                                                       0x854D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_E3                                                       0x854E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_F1                                                       0x854F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_F2                                                       0x8550
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_F3                                                       0x8551
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_G1                                                       0x8552
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_G2                                                       0x8553
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_G3                                                       0x8554
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_H1                                                       0x8555
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_H2                                                       0x8556
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU1_DIMM_H3                                                       0x8557
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_A1                                                       0x8558
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_A2                                                       0x8559
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_A3                                                       0x855A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_B1                                                       0x855B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_B2                                                       0x855C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_B3                                                       0x855D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_C1                                                       0x855E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_C2                                                       0x855F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_C3                                                       0x85D0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_D1                                                       0x85D1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_D2                                                       0x85D2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_D3                                                       0x85D3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_E1                                                       0x85D4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_E2                                                       0x85D5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_E3                                                       0x85D6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_F1                                                       0x85D7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_F2                                                       0x85D8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_F3                                                       0x85D9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_G1                                                       0x85DA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_G2                                                       0x85DB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_G3                                                       0x85DC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_H1                                                       0x85DD
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_H2                                                       0x85DE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_DISABLED_CPU2_DIMM_H3                                                       0x85DF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_A1                0x8560
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_A2                0x8561
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_A3                0x8562
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_B1                0x8563
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_B2                0x8564
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_B3                0x8565
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_C1                0x8566
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_C2                0x8567
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_C3                0x8568
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_D1                0x8569
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_D2                0x856A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_D3                0x856B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_E1                0x856C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_E2                0x856D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_E3                0x856E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_F1                0x856F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_F2                0x8570
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_F3                0x8571
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_G1                0x8572
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_G2                0x8573
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_G3                0x8574
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_H1                0x8575
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_H2                0x8576
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU1_DIMM_H3                0x8577
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_A1                0x8578
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_A2                0x8579
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_A3                0x857A
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_B1                0x857B
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_B2                0x857C
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_B3                0x857D
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_C1                0x857E
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_C2                0x857F
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_C3                0x85E0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_D1                0x85E1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_D2                0x85E2
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_D3                0x85E3
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_E1                0x85E4
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_E2                0x85E5
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_E3                0x85E6
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_F1                0x85E7
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_F2                0x85E8
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_F3                0x85E9
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_G1                0x85EA
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_G2                0x85EB
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_G3                0x85EC
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_H1                0x85ED
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_H2                0x85EE
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_MEMORY_ENCOUNTERED_A_SERIAL_PRESENCE_DETECTION_FAILURE_CPU2_DIMM_H3                0x85EF
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_POST_RECLAIM_OF_NON_CRITICAL_NVRAM_VARIABLES                                       0x8604
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BIOS_SETTINGS_ARE_CORRUPTED                                                        0x8605
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_NVRAM_VARIABLE_SPACE_WAS_CORRUPTED_AND_HAS_BEEN_REINITIALIZED                      0x8606
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_RECOVERY_BOOT_HAS_BEEN_INITIATED                                                   0x8607
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_BIOS_ACM_ERROR                                                                     0xA100
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_COMPONENT_ENCOUNTERED_A_SERR_ERROR                                             0xA421
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_EXPRESS_COMPONENT_ENCOUNTERED_A_PERR_ERROR                                     0xA5A0
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_PCI_EXPRESS_COMPONENT_ENCOUNTERED_A_SERR_ERROR                                     0xA5A1
#define IPMI_SENSOR_TYPE_SYSTEM_FIRMWARE_PROGRESS_OEM_INTEL_SKYLAKE_POST_ERROR_CODE_DXE_BOOT_SERVICES_DRIVER_NOT_ENOUGH_MEMORY_AVAILABLE_TO_SHADOW_A_LEGACY_OPTION_ROM 0xA6A0

/* Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_S2600BPB_REMOTE_DEBUG
 * Sensor Type = IPMI_SENSOR_TYPE_OEM_INTEL_S2600BPB_REMOTE_DEBUG
 */
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_REMOTE_JTAG_CONSENT 0x00
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_REMOTE_JTAG_ENABLED 0x01
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_REMOTE_JTAG_SESSION 0x02
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_REMOTE_PECI_ENABLED 0x03
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_REMOTE_PECI_SESSION 0x04

/* Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_S2600BPB_SYSTEM_FIRMWARE_SECURITY
 * Sensor Type = IPMI_SENSOR_TYPE_OEM_INTEL_S2600BPB_SYSTEM_FIRMWARE_SECURITY
 */
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_AUTHENTICATION_FAILURE_OF_BMC_FIRMWARE_IMAGE_DURING_BOOT          0x00
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_INVALID_SECURITY_REVISION_OF_BMC_FIRMWARE_IMAGE_DURING_BOOT       0x01
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_AUTHENTICATION_FAILURE_OF_BMC_FIRMWARE_IMAGE_DURING_UPDATE        0x02
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_INVALID_SECURITY_REVISION_OF_BMC_FIRMWARE_IMAGE_DURING_UPDATE     0x03
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_AUTHENTICATION_FAILURE_OF_SIGNED_REGION_DURING_UPDATE             0x04
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_AUTHENTICATION_FAILURE_OF_SIGNED_REGION_DURING_BOOT_OR_RUNTIME    0x05
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_INVALID_SECURITY_REVISION_OF_SIGNED_REGION_DURING_UPDATE          0x06
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_INVALID_SECURITY_REVISION_OF_SIGNED_REGION_DURING_BOOT_OR_RUNTIME 0x07
/* achu: not a typo, jumps to 0x0C & 0x0D */
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_FACTORY_IMAGE_BOOTED                                              0x0C
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_SYSTEM_FIRMWARE_SECURITY_FACTORY_SECURITY_REVISION_DOWNGRADED                              0x0D

/* Event Reading Type Code = IPMI_EVENT_READING_TYPE_CODE_OEM_INTEL_S2600BPB_KCS_POLICY
 * Sensor Type = IPMI_SENSOR_TYPE_OEM_INTEL_S2600BPB_KCS_POLICY
 */
/* achu: not an error, starts at 0x03 */
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_KCS_POLICY_KCS_ALLOW_ALL_MODE  0x03
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_KCS_POLICY_KCS_RESTRICTED_MODE 0x04
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_KCS_POLICY_KCS_DENY_ALL_MODE   0x05

/*
 * String arrays for above
 */

extern const char * const ipmi_oem_intel_s2600bpb_specific_remote_debug[];
extern unsigned int ipmi_oem_intel_s2600bpb_specific_remote_debug_max_index;

extern const char * const ipmi_oem_intel_s2600bpb_specific_system_firmware_security[];
extern unsigned int ipmi_oem_intel_s2600bpb_specific_system_firmware_security_max_index;

extern const char * const ipmi_oem_intel_s2600bpb_specific_kcs_policy[];
extern unsigned int ipmi_oem_intel_s2600bpb_specific_kcs_policy_max_index;

/* achu: Document is ambiguous about if this applies to event data 2 or
 * 3, so we just say "EVENT_DATA"
 */
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_EVENT_DATA_JTAG_SESSION_STATE_BITMASK 0x01
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_EVENT_DATA_JTAG_ENABLED_BITMASK       0x02
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_EVENT_DATA_JTAG_DEBUG_CONSENT_BITMASK 0x03
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_EVENT_DATA_PECI_SESSION_STATE_BITMASK 0x04
#define IPMI_OEM_INTEL_S2600BPB_SPECIFIC_REMOTE_DEBUG_EVENT_DATA_PECI_ENABLED_BITMASK       0x05

#ifdef __cplusplus
}
#endif

#endif /* IPMI_SENSOR_AND_EVENT_CODE_TABLES_OEM_INTEL_S2600BPB_SPEC_H */
