.SH "GENERAL USE"
Most users of will want to:
.LP
A) Run with --checkout to get a copy of the current configuration and
store it in a file.  The standard output can be redirected to a file
or a file can be specified with the --filename option.
.LP
B) Edit the configuration file with an editor.
.LP
C) Commit the configuration back using the --commit option and
specifying the configuration file with the --filename option.  The
configuration can be committed to multiple hosts in parallel via the
hostrange support.
