.SH "WORKAROUNDS"
With so many different vendors implementing their
own IPMI solutions, different vendors may implement their IPMI
protocols incorrectly.  The following lists the handful of
compliance issues discovered and the workarounds currently 
supported.
.LP
When possible, workarounds have been implemented so they will be
transparent to the user.  However, some will require the user to
specify a workaround be used via the -W option.
.LP
The hardware listed below may only indicate the hardware that a
problem was discovered on.  Newer versions of hardware may fix the
problems indicated below.  Similar machines from vendors may or may
not exhibit the same problems.
