#ifndef _IPMI_LAN_PARAM_SPEC_H
#define _IPMI_LAN_PARAM_SPEC_H

#define IPMI_LAN_PARAM_AUTH_TYPE_ENABLES            2 
#define IPMI_LAN_PARAM_IP_ADDR                      3 
#define IPMI_LAN_PARAM_IP_ADDR_SOURCE               4 
#define IPMI_LAN_PARAM_MAC_ADDR                     5 
#define IPMI_LAN_PARAM_SUBNET_MASK                  6 
#define IPMI_LAN_PARAM_IPV4_HEADER_PARAMETERS       7 
#define IPMI_LAN_PARAM_PRIMARY_RMCP_PORT_NO         8 
#define IPMI_LAN_PARAM_SECONDARY_RMCP_PORT_NO       9 
#define IPMI_LAN_PARAM_BMC_GENERATED_ARP_CONTROL    10 
#define IPMI_LAN_PARAM_GRATUITOUS_ARP_INTERVAL      11
#define IPMI_LAN_PARAM_DEFAULT_GATEWAY_IP_ADDR      12
#define IPMI_LAN_PARAM_DEFAULT_GATEWAY_MAC_ADDR     13
#define IPMI_LAN_PARAM_BACKUP_GATEWAY_IP_ADDR       14
#define IPMI_LAN_PARAM_BACKUP_GATEWAY_MAC_ADDR      15
#define IPMI_LAN_PARAM_COMMUNITY_STRING             16
#define IPMI_LAN_PARAM_NO_OF_DESTINATIONS           17
#define IPMI_LAN_PARAM_DESTINATION_TYPE             18
#define IPMI_LAN_PARAM_DESTINATION_ADDRESSES        19

#endif
