\input texinfo @c -*-texinfo-*-
@c This file uses the @command command introduced in Texinfo 4.0.
@c %**start of header
@setfilename fish.info
@settitle Free IPMI SHell - an extensible console based shell for managing large number of IPMI compatible systems.
@finalout
@setchapternewpage odd
@c %**end of header

@include vers-fish.texi

@ifinfo
This file documents the @command{fish} command which Free IPMI SHell - an extensible console based shell for managing large number of IPMI compatible systems.

Copyright (C) 2003 FreeIPMI Core Team

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.
@end ifinfo

@titlepage
@title fish
@subtitle Free IPMI SHell - an extensible console based shell for managing large number of IPMI compatible systems.
@subtitle for fish Version @value{VERSION}
@author by Anand Babu

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2003 FreeIPMI Core Team

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.
@end titlepage

@c All the nodes can be updated using the EMACS command
@c texinfo-every-node-update, which is normally bound to C-c C-u C-e.
@node Top, Instructions, (dir), (dir)

@ifinfo
This file documents the @command{fish} command to Free IPMI SHell - an extensible console based shell for managing large number of IPMI compatible systems..
@end ifinfo

@c All the menus can be updated with the EMACS command
@c texinfo-all-menus-update, which is normally bound to C-c C-u C-a.
@menu
* Instructions::                How to read this manual. 
* Overview::                    Preliminary information.
* Sample::                      Sample output from @command{fish}.
* Invoking fish::               How to run @command{fish}.
* Problems::                    Reporting bugs.
* Concept Index::               Index of concepts.
* Copying::                     How you can copy and share @command{fish}.
@end menu

@node Instructions, Overview, Top, Top
@chapter How to Read This Manual

@cindex reading
@cindex manual, how to read
@cindex how to read
To read this manual, begin at the beginning, reading from left to right
and top to bottom, until you get to the end.  Then stop.  You may pause
for a beer anywhere in the middle as well, if you wish.  (Please note,
however, that The King strongly advises against heavy use of
prescription pharmaceuticals, based on his extensive personal and
professional experience.)

@node Overview, Sample, Instructions, Top
@chapter Overview
@cindex greetings
@cindex overview

The GNU @command{fish} program produces a familiar, friendly greeting.
It allows nonprogrammers to use a classic computer science tool which
would otherwise be unavailable to them.  Because it is protected by the
GNU General Public License, users are free to share and change it.

GNU @command{fish} was written by Anand Babu.

@node Sample, Invoking fish, Overview, Top
@chapter Sample Output
@cindex sample

Here are some realistic examples of running @command{fish}.

This is the output of the command @samp{fish}:

@example
hello, world!
@end example

This is the output of the command @samp{fish --help}:

@example
Usage: fish [OPTION...] [FILE...]
Free IPMI SHell - an extensible console based shell for managing large number of IPMI compatible systems.

      --brief                Shorten output
  -q, --quiet, --silent      Inhibit usual output
  -v, --verbose              Print more information
  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

Report bugs to <ab@@gnu.org.in>.
@end example

@node Invoking fish, Problems, Sample, Top
@chapter Invoking @command{fish}
@cindex invoking
@cindex version
@cindex options
@cindex usage
@cindex help
@cindex getting help

The format for running the @command{fish} program is:

@example
fish @var{option} @dots{}
@end example

@code{fish} supports the following options:

@c Formatting copied from the Texinfo 4.0 manual.
@table @code
@item --quiet
@itemx --silent
@itemx -q
Inhibit usual output.

@item --brief
Shorten output.

@item --verbose
@itemx -v
Print more information.

@item --help
@itemx -?
Print an informative help message describing the options and then exit
successfully.

@item --usage
Briefly list the options.

@item --version
@itemx -V
Print the version number of @command{fish} on the standard output
and then exit successfully.
@end table

@node Problems, Concept Index, Invoking fish, Top
@chapter Reporting Bugs
@cindex bugs
@cindex problems

If you find a bug in @command{fish}, please send electronic mail to
@email{ab@@gnu.org.in}.  Include the version number, which you can find by
running @w{@samp{fish --version}}.  Also include in your message the
output that the program produced and the output you expected.@refill

If you have other questions, comments or suggestions about
@command{fish}, contact the author via electronic mail to
@email{ab@@gnu.org.in}.  The author will try to help you out, although he
may not have time to fix your problems.

@node Concept Index, Copying, Problems, Top
@unnumbered Concept Index

@cindex tail recursion
@printindex cp

@shortcontents
@contents

@node Copying, , Concept Index, Top
@include gpl.texinfo


@bye
