/*
   Copyright (C) 2003-2009 FreeIPMI Core Team

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA.
 */

#ifndef _IPMI_SENSOR_AND_EVENT_CODE_TABLES_SPEC_H
#define _IPMI_SENSOR_AND_EVENT_CODE_TABLES_SPEC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/************************************************
 * Generic Event Reading Type Code Offsets      *
 ************************************************/

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_NON_CRITICAL_GOING_LOW     0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_NON_CRITICAL_GOING_HIGH    0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_CRITICAL_GOING_LOW         0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_CRITICAL_GOING_HIGH        0x03
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_NON_RECOVERABLE_GOING_LOW  0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_LOWER_NON_RECOVERABLE_GOING_HIGH 0x05
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_NON_CRITICAL_GOING_LOW     0x06
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_NON_CRITICAL_GOING_HIGH    0x07
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_CRITICAL_GOING_LOW         0x08
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_CRITICAL_GOING_HIGH        0x09
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_NON_RECOVERABLE_GOING_LOW  0x0A
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_THRESHOLD_UPPER_NON_RECOVERABLE_GOING_HIGH 0x0B

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_STATE_TRANSITION_TO_IDLE   0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_STATE_TRANSITION_TO_ACTIVE 0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_STATE_TRANSITION_TO_BUSY   0x02

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_DEASSERTED 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_STATE_ASSERTED   0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_PREDICTIVE_FAILURE_DEASSERTED 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_PREDICTIVE_FAILURE_ASSERTED   0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_LIMIT_NOT_EXCEEDED 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_LIMIT_EXCEEDED     0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_PERFORMANCE_MET  0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_PERFORMANCE_LAGS 0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_OK                               0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_NON_CRITICAL_FROM_OK             0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_CRITICAL_FROM_LESS_SEVERE        0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_NON_RECOVERABLE_FROM_LESS_SEVERE 0x03
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_NON_CRITICAL_FROM_MORE_SEVERE    0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_CRITICAL_FROM_NON_RECOVERABLE    0x05
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_TRANSITION_TO_NON_RECOVERABLE                  0x06
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_MONITOR                                        0x07
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_SEVERITY_INFORMATIONAL                                  0x08

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_DEVICE_PRESENT_DEVICE_PRESENT 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_DEVICE_PRESENT_DEVICE_ABSENT  0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_DEVICE_ENABLED_DEVICE_DISABLED 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_DEVICE_ENABLED_DEVICE_ENABLED  0x01

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_RUNNING    0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_IN_TEST    0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_POWER_OFF  0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_ON_LINE    0x03
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_OFF_LINE   0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_OFF_DUTY   0x05
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_DEGRADED   0x06
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_TRANSITION_TO_POWER_SAVE 0x07
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_TRANSITION_AVAILABILITY_INSTALL_ERROR            0x08

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_FULLY_REDUNDANT                                                0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_REDUNDANCY_LOST                                                0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_REDUNDANCY_DEGRADED                                            0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_REDUNDANT              0x03
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_NON_REDUNDANT_SUFFICIENT_RESOURCES_FROM_INSUFFICIENT_RESOURCES 0x04
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_NON_REDUNDANT_INSUFFICIENT_RESOURCES                           0x05
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_REDUNDANCY_DEGRADED_FROM_FULLY_REDUNDANT                       0x06
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_REDUNDANCY_REDUNDANCY_DEGRADED_FROM_NON_REDUNDANT                         0x07

#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_ACPI_POWER_STATE_D0_POWER_STATE 0x00
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_ACPI_POWER_STATE_D1_POWER_STATE 0x01
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_ACPI_POWER_STATE_D2_POWER_STATE 0x02
#define IPMI_GENERIC_EVENT_READING_TYPE_CODE_ACPI_POWER_STATE_D3_POWER_STATE 0x03
  
/************************************************
 * Sensor Type Code Offsets                     *
 ************************************************/

#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_GENERAL_CHASSIS_INTRUSION 0x00
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_DRIVE_BAY_INTRUSION       0x01
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_IO_CARD_AREA_INTRUSION    0x02
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_PROCESSOR_AREA_INTRUSION  0x03
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_LAN_LEASH_LOST            0x04
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_UNAUTHORIZED_DOCK         0x05
#define IPMI_SENSOR_TYPE_CODE_PHYSICAL_SECURITY_FAN_AREA_INTRUSION        0x06

#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_SECURE_MODE_VIOLATION_ATTEMPT                      0x00
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_USER_PASSWORD          0x01
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_ATTEMPT_SETUP_PASSWORD 0x02
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_PRE_BOOT_PASSWORD_VIOLATION_NETWORK_BOOT_PASSWORD  0x03
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_OTHER_PRE_BOOT_PASSWORD_VIOLATION                  0x04
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_SECURITY_VIOLATION_ATTEMPT_OUT_OF_BAND_ACCESS_PASSWORD_VIOLATION              0x05
  
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_IERR                                          0x00
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_THERMAL_TRIP                                  0x01
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_FRB1_BIST_FAILURE                             0x02
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_FRB2_HANG_IN_POST_FAILURE                     0x03
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_FRB3_PROCESSOR_STARTUP_INITIALIZATION_FAILURE 0x04
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_CONFIGURATION_ERROR                           0x05
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_SMBIOS_UNCORRECTABLE_CPU_COMPLEX_ERROR        0x06
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_PROCESSOR_PRESENCE_DETECTED                   0x07
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_PROCESSOR_DISABLED                            0x08
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_TERMINATOR_PRESENCE_DETECTED                  0x09
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_PROCESSOR_AUTOMATICALLY_THROTTLED             0x0A
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_MACHINE_CHECK_EXCEPTION                       0x0B
#define IPMI_SENSOR_TYPE_CODE_PROCESSOR_CORRECTABLE_MACHINE_CHECK_ERROR               0x0C

#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_PRESENCE_DETECTED                           0x00
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_POWER_SUPPLY_FAILURE_DETECTED               0x01
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_PREDICTIVE_FAILURE                          0x02
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_POWER_SUPPLY_INPUT_LOST_AC_DC               0x03
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_POWER_SUPPLY_INPUT_LOST_OR_OUT_OF_RANGE     0x04
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_POWER_SUPPLY_INPUT_OUT_OF_RANGE_BUT_PRESENT 0x05
#define IPMI_SENSOR_TYPE_CODE_POWER_SUPPLY_CONFIGURATION_ERROR                         0x06

#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_POWER_OFF_POWER_DOWN        0x00
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_POWER_CYCLE                 0x01
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_240VA_POWER_DOWN            0x02
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_INTERLOCK_POWER_DOWN        0x03
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_AC_LOST                     0x04
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_SOFT_POWER_CONTROL_FAILURE  0x05
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_POWER_UNIT_FAILURE_DETECTED 0x06
#define IPMI_SENSOR_TYPE_CODE_POWER_UNIT_PREDICTIVE_FAILURE          0x07


#define IPMI_SENSOR_TYPE_CODE_MEMORY_CORRECTABLE_MEMORY_ERROR                       0x00
#define IPMI_SENSOR_TYPE_CODE_MEMORY_UNCORRECTABLE_MEMORY_ERROR                     0x01
#define IPMI_SENSOR_TYPE_CODE_MEMORY_PARITY                                         0x02
#define IPMI_SENSOR_TYPE_CODE_MEMORY_MEMORY_SCRUB_FAILED                            0x03
#define IPMI_SENSOR_TYPE_CODE_MEMORY_MEMORY_DEVICE_DISABLED                         0x04
#define IPMI_SENSOR_TYPE_CODE_MEMORY_CORRECTABLE_MEMORY_ERROR_LOGGING_LIMIT_REACHED 0x05
#define IPMI_SENSOR_TYPE_CODE_MEMORY_PRESENCE_DETECTED                              0x06
#define IPMI_SENSOR_TYPE_CODE_MEMORY_CONFIGURATION_ERROR                            0x07
#define IPMI_SENSOR_TYPE_CODE_MEMORY_SPARE                                          0x08
#define IPMI_SENSOR_TYPE_CODE_MEMORY_MEMORY_AUTOMATICALLY_THROTTLED                 0x09
#define IPMI_SENSOR_TYPE_CODE_MEMORY_CRITICAL_OVERTEMPERATURE                       0x0A

#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_DRIVE_PRESENCE                             0x00
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_DRIVE_FAULT                                0x01
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_PREDICTIVE_FAILURE                         0x02
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_HOT_SPARE                                  0x03
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_CONSISTENCY_CHECK_PARITY_CHECK_IN_PROGRESS 0x04
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_IN_CRITICAL_ARRAY                          0x05
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_IN_FAILED_ARRAY                            0x06
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_REBUILD_REMAP_IN_PROGRESS                  0x07
#define IPMI_SENSOR_TYPE_CODE_DRIVE_SLOT_REBUILD_REMAP_ABORTED                      0x08

#define IPMI_SENSOR_TYPE_CODE_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_ERROR    0x00
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_HANG     0x01
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_FIRMWARE_PROGRESS_SYSTEM_FIRMWARE_PROGRESS 0x02

#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_CORRECTABLE_MEMORY_ERROR_LOGGING_DISABLED        0x00
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_EVENT_TYPE_LOGGING_DISABLED                      0x01
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_LOG_AREA_RESET_CLEARED                           0x02
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_ALL_EVENT_LOGGING_DISABLED                       0x03
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_SEL_FULL                                         0x04
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_SEL_ALMOST_FULL                                  0x05
#define IPMI_SENSOR_TYPE_CODE_EVENT_LOGGING_DISABLED_CORRECTABLE_MACHINE_CHECK_ERROR_LOGGING_DISABLED 0x06

#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_BIOS_WATCHDOG_RESET                       0x00
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_RESET                         0x01
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_SHUT_DOWN                     0x02
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_POWER_DOWN                    0x03
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_POWER_CYCLE                   0x04
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_NMI_DIAGNOSTIC_INTERRUPT      0x05
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_EXPIRED_STATUS_ONLY           0x06
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG1_OS_WATCHDOG_PRE_TIMEOUT_INTERRUPT_NON_NMI 0x07

#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_SYSTEM_RECONFIGURED                  0x00
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_OEM_SYSTEM_BOOT_EVENT                0x01
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_UNDETERMINED_SYSTEM_HARDWARE_FAILURE 0x02
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_ENTRY_ADDED_TO_AUXILIARY_LOG         0x03
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_PEF_ACTION                           0x04
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_EVENT_TIMESTAMP_CLOCK_SYNC                 0x05

#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_FRONT_PANEL_NMI_DIAGNOSTIC_INTERRUPT 0x00
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_BUS_TIMEOUT                          0x01
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_IO_CHANNEL_CHECK_NMI                 0x02
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_SOFTWARE_NMI                         0x03
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_PCI_PERR                             0x04
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_PCI_SERR                             0x05
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_EISA_FAIL_SAFE_TIMEOUT               0x06
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_BUS_CORRECTABLE_ERROR                0x07
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_BUS_UNCORRECTABLE_ERROR              0x08
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_FATAL_NMI                            0x09
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_BUS_FATAL_ERROR                      0x0A
#define IPMI_SENSOR_TYPE_CODE_CRITICAL_INTERRUPT_BUS_DEGRADED                         0x0B

#define IPMI_SENSOR_TYPE_CODE_BUTTON_SWITCH_POWER_BUTTON_PRESSED       0x00
#define IPMI_SENSOR_TYPE_CODE_BUTTON_SWITCH_SLEEP_BUTTON_PRESSED       0x01
#define IPMI_SENSOR_TYPE_CODE_BUTTON_SWITCH_RESET_BUTTON_PRESSED       0x02
#define IPMI_SENSOR_TYPE_CODE_BUTTON_SWITCH_FRU_LATCH_OPEN             0x03
#define IPMI_SENSOR_TYPE_CODE_BUTTON_SWITCH_FRU_SERVICE_REQUEST_BUTTON 0x04

#define IPMI_SENSOR_TYPE_CODE_CHIP_SET_SOFT_POWER_CONTROL_FAILURE 0x00
#define IPMI_SENSOR_TYPE_CODE_CHIP_SET_THERMAL_TRIP               0x01

#define IPMI_SENSOR_TYPE_CODE_CABLE_INTERCONNECT_IS_CONNECTED        0x00
#define IPMI_SENSOR_TYPE_CODE_CABLE_INTERCONNECT_CONFIGURATION_ERROR 0x01

#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_INITIATED_BY_POWER_UP                     0x00
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_INITIATED_BY_HARD_RESET                   0x01
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_INITIATED_BY_WARM_RESET                   0x02
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_USER_REQUESTED_PXE_BOOT                   0x03
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_AUTOMATIC_BOOT_TO_DIAGNOSTIC              0x04
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_OS_RUN_TIME_SOFTWARE_INITIATED_HARD_RESET 0x05
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_OS_RUN_TIME_SOFTWARE_INITIATED_WARM_RESET 0x06
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_BOOT_INITIATED_SYSTEM_RESTART                            0x07

#define IPMI_SENSOR_TYPE_CODE_BOOT_ERROR_NO_BOOTABLE_MEDIA                                 0x00
#define IPMI_SENSOR_TYPE_CODE_BOOT_ERROR_NON_BOOTABLE_DISKETTE_LEFT_IN_DRIVE               0x01
#define IPMI_SENSOR_TYPE_CODE_BOOT_ERROR_PXE_SERVER_NOT_FOUND                              0x02
#define IPMI_SENSOR_TYPE_CODE_BOOT_ERROR_INVALID_BOOT_SECTOR                               0x03
#define IPMI_SENSOR_TYPE_CODE_BOOT_ERROR_TIMEOUT_WAITING_FOR_USER_SELECTION_OF_BOOT_SOURCE 0x04

#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_A_BOOT_COMPLETED                         0x00
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_C_BOOT_COMPLETED                         0x01
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_PXE_BOOT_COMPLETED                       0x02
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_DIAGNOSTIC_BOOT_COMPLETED                0x03
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_CD_ROM_BOOT_COMPLETED                    0x04
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_ROM_BOOT_COMPLETED                       0x05
#define IPMI_SENSOR_TYPE_CODE_OS_BOOT_BOOT_COMPLETED_BOOT_DEVICE_NOT_SPECIFIED 0x06

#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_CRITICAL_STOP_DURING_OS_LOAD   0x00
#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_RUN_TIME_CRITICAL_STOP         0x01
#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_OS_GRACEFUL_STOP               0x02
#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_OS_GRACEFUL_SHUTDOWN           0x03
#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_SOFT_SHUTDOWN_INITIATED_BY_PEF 0x04
#define IPMI_SENSOR_TYPE_CODE_OS_CRITICAL_STOP_AGENT_NOT_RESPONDING           0x05

#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_FAULT_STATUS_ASSERTED                        0x00
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_IDENTIFY_STATUS_ASSERTED                     0x01
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_CONNECTOR_DEVICE_INSTALLED_ATTACHED     0x02
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_CONNECTOR_READY_FOR_DEVICE_INSTALLATION 0x03
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_CONNECTOR_READY_FOR_DEVICE_REMOVAL      0x04
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_POWER_IS_OFF                            0x05
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_CONNECTOR_DEVICE_REMOVAL_REQUEST        0x06
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_INTERLOCK_ASSERTED                           0x07
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_IS_DISABLED                             0x08
#define IPMI_SENSOR_TYPE_CODE_SLOT_CONNECTOR_SLOT_HOLDS_SPARE_DEVICE                      0x09

#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S0_G0                             0x00
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S1                                0x01
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S2                                0x02
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S3                                0x03
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S4                                0x04
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S5_G2                             0x05
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S4_S5_SOFT_OFF                    0x06
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_G3_MECHANICAL_OFF                 0x07
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_SLEEPING_IN_AN_S1_S2_OR_S3_STATES 0x08
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_G1_SLEEPING                       0x09
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_S5_ENTERED_BY_OVERRIDE            0x0A
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_LEGACY_ON_STATE                   0x0B
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_LEGACY_OFF_STATE                  0x0C
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_UNSPECIFIED                       0x0D
#define IPMI_SENSOR_TYPE_CODE_SYSTEM_ACPI_POWER_STATE_UNKNOWN                           0x0E

#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_TIMER_EXPIRED   0x00
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_HARD_RESET      0x01
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_POWER_DOWN      0x02
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_POWER_CYCLE     0x03
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_RESERVED1       0x04
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_RESERVED2       0x05
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_RESERVED3       0x06
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_RESERVED4       0x07
#define IPMI_SENSOR_TYPE_CODE_WATCHDOG2_TIMER_INTERRUPT 0x08

#define IPMI_SENSOR_TYPE_CODE_PLATFORM_ALERT_PLATFORM_GENERATED_PAGE       0x00
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_ALERT_PLATFORM_GENERATED_LAN_ALERT  0x01
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_ALERT_PLATFORM_EVENT_TRAP_GENERATED 0x02
#define IPMI_SENSOR_TYPE_CODE_PLATFORM_ALERT_PLATFORM_GENERATED_SNMP_TRAP  0x03

#define IPMI_SENSOR_TYPE_CODE_ENTITY_PRESENCE_ENTITY_PRESENT  0x00
#define IPMI_SENSOR_TYPE_CODE_ENTITY_PRESENCE_ENTITY_ABSENT   0x01
#define IPMI_SENSOR_TYPE_CODE_ENTITY_PRESENCE_ENTITY_DISABLED 0x02

#define IPMI_SENSOR_TYPE_CODE_LAN_HEARTBEAT_LOST 0x00
#define IPMI_SENSOR_TYPE_CODE_LAN_HEARTBEAT      0x01

#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_SENSOR_ACCESS_DEGRADED_OR_UNAVAILABLE     0x00
#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_CONTROLLER_ACCESS_DEGRADED_OR_UNAVAILABLE 0x01
#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_MANAGEMENT_CONTROLLER_OFF_LINE            0x02
#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_MANAGEMENT_CONTROLLER_UNAVAILABLE         0x03
#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_SENSOR_FAILURE                            0x04
#define IPMI_SENSOR_TYPE_CODE_MANAGEMENT_SUBSYSTEM_HEALTH_FRU_FAILURE                               0x05

#define IPMI_SENSOR_TYPE_CODE_BATTERY_BATTERY_LOW               0x00
#define IPMI_SENSOR_TYPE_CODE_BATTERY_BATTERY_FAILED            0x01
#define IPMI_SENSOR_TYPE_CODE_BATTERY_BATTERY_PRESENCE_DETECTED 0x02

#define IPMI_SENSOR_TYPE_CODE_SESSION_AUDIT_SESSION_ACTIVATED            0x00
#define IPMI_SENSOR_TYPE_CODE_SESSION_AUDIT_SESSION_DEACTIVATED          0x01
#define IPMI_SENSOR_TYPE_CODE_SESSION_AUDIT_INVALID_USERNAME_OR_PASSWORD 0x02

#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY                        0x00
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_FIRMWARE_OR_SOFTWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY            0x01
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_HARDWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY               0x02
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_FIRMWARE_OR_SOFTWARE_INCOMPATABILITY_DETECTED_WITH_ASSOCIATED_ENTITY   0x03
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_ENTITY_IS_OF_AN_INVALID_OR_UNSUPPORTED_HARDWARE_VERSION                0x04
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_ENTITY_CONTAINS_AN_INVALID_OR_UNSUPPORTED_FIRMWARE_OR_SOFTWARE_VERSION 0x05
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_HARDWARE_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL         0x06
#define IPMI_SENSOR_TYPE_CODE_VERSION_CHANGE_SOFTWARE_OR_FW_CHANGE_DETECTED_WITH_ASSOCIATED_ENTITY_WAS_SUCCESSFUL   0x07

#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_NOT_INSTALLED            0x00
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_INACTIVE                 0x01
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_ACTIVATION_REQUESTED     0x02
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_ACTIVATION_IN_PROGRESS   0x03
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_ACTIVE                   0x04
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_DEACTIVATION_REQUESTED   0x05
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_DEACTIVATION_IN_PROGRESS 0x06
#define IPMI_SENSOR_TYPE_CODE_FRU_STATE_FRU_COMMUNICATION_LOST       0x07

#ifdef __cplusplus
}
#endif

#endif
