(define (commit-username section-name username)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-username 1 username))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-username 2 username))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-username 3 username))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-username 4 username))))

(define (commit-enable-user section-name user-status)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-enable-user 1 user-status))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-enable-user 2 user-status))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-enable-user 3 user-status))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-enable-user 4 user-status))))

(define (commit-clear-password section-name password-status)
  (cond 
   ((string-ci=? section-name "user1")
    (if password-status (fi-set-bmc-user-password 1 "") #t))
   ((string-ci=? section-name "user2")
    (if password-status (fi-set-bmc-user-password 2 "") #t))
   ((string-ci=? section-name "user3")
    (if password-status (fi-set-bmc-user-password 3 "") #t))
   ((string-ci=? section-name "user4")
    (if password-status (fi-set-bmc-user-password 4 "") #t))))

(define (commit-password section-name password)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-password 1 password))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-password 2 password))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-password 3 password))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-password 4 password))))

(define (commit-lan-enable-ipmi-msgs section-name enable-ipmi-msgs)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-lan-channel-access 1 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-lan-channel-access 2 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-lan-channel-access 3 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-lan-channel-access 4 enable-ipmi-msgs 0 0 #f #f))))

(define (commit-lan-enable-link-auth section-name enable-link-auth)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-lan-channel-access 1 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-lan-channel-access 2 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-lan-channel-access 3 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-lan-channel-access 4 0 enable-link-auth 0 #f #f))))

(define (commit-lan-enable-restrict-to-callback section-name enable-restrict-to-callback)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-lan-channel-access 1 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-lan-channel-access 2 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-lan-channel-access 3 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-lan-channel-access 4 0 0 enable-restrict-to-callback #f #f))))

(define (commit-lan-privilege-limit section-name privilege-limit)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-lan-channel-access 1 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-lan-channel-access 2 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-lan-channel-access 3 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-lan-channel-access 4 0 0 0 privilege-limit #f))))

(define (commit-lan-session-limit section-name session-limit)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-lan-channel-access 1 0 0 0 #f session-limit))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-lan-channel-access 2 0 0 0 #f session-limit))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-lan-channel-access 3 0 0 0 #f session-limit))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-lan-channel-access 4 0 0 0 #f session-limit))))

(define (commit-serial-enable-ipmi-msgs section-name enable-ipmi-msgs)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-serial-channel-access 1 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-serial-channel-access 2 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-serial-channel-access 3 enable-ipmi-msgs 0 0 #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-serial-channel-access 4 enable-ipmi-msgs 0 0 #f #f))))

(define (commit-serial-enable-link-auth section-name enable-link-auth)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-serial-channel-access 1 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-serial-channel-access 2 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-serial-channel-access 3 0 enable-link-auth 0 #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-serial-channel-access 4 0 enable-link-auth 0 #f #f))))

(define (commit-serial-enable-restrict-to-callback section-name enable-restrict-to-callback)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-serial-channel-access 1 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-serial-channel-access 2 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-serial-channel-access 3 0 0 enable-restrict-to-callback #f #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-serial-channel-access 4 0 0 enable-restrict-to-callback #f #f))))

(define (commit-serial-privilege-limit section-name privilege-limit)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-serial-channel-access 1 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-serial-channel-access 2 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-serial-channel-access 3 0 0 0 privilege-limit #f))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-serial-channel-access 4 0 0 0 privilege-limit #f))))

(define (commit-serial-session-limit section-name session-limit)
  (cond 
   ((string-ci=? section-name "user1")
    (fi-set-bmc-user-serial-channel-access 1 0 0 0 #f session-limit))
   ((string-ci=? section-name "user2")
    (fi-set-bmc-user-serial-channel-access 2 0 0 0 #f session-limit))
   ((string-ci=? section-name "user3")
    (fi-set-bmc-user-serial-channel-access 3 0 0 0 #f session-limit))
   ((string-ci=? section-name "user4")
    (fi-set-bmc-user-serial-channel-access 4 0 0 0 #f session-limit))))


(define user-keys-validator 
  '(("username" valid-username-password? get-string commit-username)
    ("enable_user" valid-boolean? get-boolean commit-enable-user)
    ("clear_password" valid-boolean? get-boolean commit-clear-password)
    ("password" valid-username-password? get-string  commit-password)
    ("lan_enable_ipmi_Msgs" valid-boolean? get-boolean commit-lan-enable-ipmi-msgs)
    ("lan_enable_link_auth" valid-boolean? get-boolean commit-lan-enable-link-auth)
    ("lan_enable_restrict_to_callback" valid-boolean? get-boolean commit-lan-enable-restrict-to-callback)
    ("lan_privilege_limit" valid-privilege-limit? get-privilege-limit commit-lan-privilege-limit)
    ("lan_session_limit" valid-integer? get-integer commit-lan-session-limit)
    ("serial_enable_ipmi_msgs" valid-boolean? get-boolean commit-serial-enable-ipmi-msgs)
    ("serial_enable_link_auth" valid-boolean? get-boolean commit-serial-enable-link-auth)
    ("serial_enable_restrict_to_callback" valid-boolean? get-boolean commit-serial-enable-restrict-to-callback)
    ("serial_privilege_limit" valid-privilege-limit? get-privilege-limit commit-serial-privilege-limit)
    ("serial_session_limit" valid-integer? get-boolean commit-serial-session-limit)
    ;; You can add more in the form of 
    ;; (KEYSTRING VALIDATION-PROC CONVERTION-PROC BMC-COMMIT-PROC)
    ))

