#!/bin/sh
#
# chkconfig: 2345 99 01
# description: gmond startup script
#
DAEMON=/usr/sbin/bmc-watchdog

. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
   start)
      echo -n "Starting bmc-watchdog: "
      [ -f $DAEMON ] || exit 1

      # Default deamon mode
      #
      # pre-timeout interrupt = NMI
      # action = none
      # pre-timeout-interval = 30 seconds
      # initial-countdown = 900 seconds (15 mins)
      # reset-period = 60 seconds

      daemon -20 $DAEMON -d -p 2 -a 0 -z 30 -i 900 -e 60
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && touch /var/lock/subsys/bmc-watchdog
	;;

  stop)
      echo -n "Shutting down bmc-watchdog: "
      killproc bmc-watchdog 
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/bmc-watchdog
	;;

  restart|reload)
   	$0 stop
   	$0 start
   	RETVAL=$?
	;;
  status)
   	status bmc-watchdog
   	RETVAL=$?
	;;
  condrestart)
        if test -e /var/lock/subsys/bmc-watchdog; then \
            $0 stop; \
            $0 start; \
            RETVAL=$?; \
        fi
        ;;
  *)
	echo "Usage: $0 {start|stop|restart|status|condrestart}"
	exit 1
esac

exit $RETVAL
