#!/bin/sh
#
# chkconfig: - 99 01
# description: bmc-watchdog startup script
#
DAEMON=/usr/sbin/bmc-watchdog
LOCKFILE=/var/lock/subsys/freeipmi-bmc-watchdog

. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
   start)
      echo -n "Starting bmc-watchdog: "
      [ -f $DAEMON ] || exit 1

      # Default deamon mode
      #
      # timer use = SMS/OS
      # pre-timeout interrupt = none
      # action = reset
      # -F, -P, -L, -S, -O - clear flags
      # initial-countdown = 900 seconds (15 mins)
      # reset-period = 60 seconds

      daemon -20 $DAEMON -d -u 4 -p 0 -a 1 -F -P -L -S -O -i 900 -e 60 
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && touch /var/lock/subsys/freeipmi-bmc-watchdog
	;;

  stop)
      echo -n "Shutting down bmc-watchdog: "
      killproc bmc-watchdog 
      RETVAL=$?
      echo
      [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/freeipmi-bmc-watchdog
	;;

  restart|reload)
   	$0 stop
   	$0 start
   	RETVAL=$?
	;;
  status)
   	status bmc-watchdog
   	RETVAL=$?
	;;
  condrestart)
        if test -e /var/lock/subsys/freeipmi-bmc-watchdog; then \
            $0 stop; \
            $0 start; \
            RETVAL=$?; \
        fi
        ;;
  *)
	echo "Usage: $0 {start|stop|restart|status|condrestart}"
	exit 1
esac

exit $RETVAL
